runtime: python27
api_version: 1
threadsafe: true

handlers:
# Referance HP's Root
- url: /
  static_files: webapp/dist/index.html
  upload: webapp/dist/index.html

- url: /static
  static_dir: webapp/dist/static

- url: /.*
  script: main.app

- url: /admin/console/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /api/manifest/add
  script: main.app
  login: admin

- url: /manifest/upload
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
