runtime: python27
api_version: 1
threadsafe: true

handlers:
# Referance HP's Root
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /index.js
  static_files: webapp/index.js
  upload: webapp/index.js

- url: /api/manifest/search_manifest/.*
  script: main.app

- url: /api/manifest/add_manifest
  script: main.app
  login: admin

- url: /upload/manifest
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest